### ISSUE TITLE
Traduction 10.9

### ISSUE THREAD

**Issue by ssAxl** [FoolEcho/vtmb-up#3]
Bonjour,

Avez-vous prévue une traduction pour la version 10.9?

Cordialement

**Comment by Sanghelyos** [comment]
Bonjour, plutôt la version 11 non ? Elle est sortie vers le milieu du mois.

**Comment by FoolEcho** [comment]
Je ne sais pas. Werner ne me donne plus de nouvelles tout en continuant des patchs... J'ai besoin de savoir où il en est et vu qu'il ne pose pas de tag dans son code je ne peux pas repartir de ses modifications à l'aveugle.

Ça dépendra également du volume de modifications... Il est probable que je saute directement à la dernière version en date et que je laisse les intermédiaires que j'ai ratées.

**Comment by Sanghelyos** [comment]
D'ailleurs, j'en profite pour remonter une tite erreur, quand on parle au flic, juste en montant à bord du Elizabeth Dane, (j'utilise le UP 10.6 fr, j'ai pas trouvé plus récent, c'est bien le dernier en version FR ?) le dernier choix de dialogue est en anglais.

**Comment by FoolEcho** [comment]
Quelle phrase ? Je ne vois pas...

**Comment by Sanghelyos** [comment]
![image](https://user-images.githubusercontent.com/12989497/131257529-5bc08748-5bd3-4a41-9a73-0270ddccf9d3.png)
Bon, ça ressemble plus à un placeholder vu que dans le contexte ça veut pas dire grand chose, donc ça viens peut-être du jeu ou du patch en lui-même. Mais autant vérifier.

**Comment by FoolEcho** [comment]
De mémoire tu n'es pas censé être si près pour ce dialogue. 
Me faudrait ta sauvegarde à ce niveau...

**Comment by Sanghelyos** [comment]
J'ai du revenir en arrière pour ça, je n'ai pas de sauvegarde qui date d'avant le dialogue initial, là je lui reparle juste.

**Comment by FoolEcho** [comment]
Tu n'es pas bloqué du coup ?

**Comment by Sanghelyos** [comment]
Non non j'ai pu continuer, ca ferme le dialogue quand je dis ça. C'est juste le texte du coup, mais vu que ça a plus l'air d'une erreur et que c'est pas supposé apparaître je pense pas que tu y puisses grand chose.

**Comment by FoolEcho** [comment]
Pour revenir à la 10.9, il me reste à l'installer pour vérifier rapidement. Si c'est ok je ferai comme d'habitude, un post pour avertir de la mise à disposition.

**Comment by ssAxl** [comment]
Super merci!
Désolé de ré-ouvrir ce post, mais je tenais vraiment et sincèrement à vous remercier pour le boulot accompli. C'est super de voir qu'une communauté active tourne toujours autour de ce jeu!!!! J'espère que le patch 11.0fr pourra voir également le jour, mais c'est encore une fois génial d'avoir cette version.

Merci et endcore désolé pour la ré-ouverture ;)

Axl

**Comment by FoolEcho** [comment]
Y a pas de mal.

Avec les vacances des uns et des autres, ça a pris un peu de temps mais le patch fr 10.9 est en ligne : https://www.patches-scrolls.de/patch/4647/7/75326 .

Pour le moment, je ne peux pas faire la com' habituelle, le site où je la fais d'ordinaire paraît en carafe... :\

**Comment by ssAxl** [comment]
Ola,

Oui j'imagine que tu parles de rpgfrance. Ca fait quelques jours qu'ils est down.
J'ai pu avoir quelques mots avec Wesp5 également sur moddb au sujet de la vf il y a quelques jours. Il devrait donner des news quand la v11 sera finalisée.

Merci pour tout ce boulot en tout cas! Super jeu et belle communauté!

Axl

**Comment by ssAxl** [comment]
Hello, 

Je viens de découvrir la trad'! Super boulot! Merci!
J'ai relancé une partie,  et j'ai vu que le paquet de BubbleBum (dans la salle d'arcade) n'est pas traduit.
Rien de grave, c'est un détail, c'est juste pour faire remonter au cas où tu fasse la chasse à ce genre de chose.

Merci encore!
Axl
